FROM golang:1.25-alpine

RUN apk add --no-cache \
    gcc \
    musl-dev \
    libwebp-dev \
    pkgconfig \
    ca-certificates \
    git \
    curl

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENV GOFLAGS=-mod=mod

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]